# This is a basic workflow to help you get started with Actions

name: Check CISA Vulnerabilities

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Vulnerability Script
        shell: pwsh
        run: |
          # Importa a função e executa
          . ./intel-cisa-feed.ps1
